### ISSUE TITLE
#1170 - mysql

### ISSUE THREAD

**Issue by smixy** [phpdave11/php-survey-builder#4]
From schema.sql in the last query I got this error:
#1170 - BLOB/TEXT column 'question_id' used in key specification without a key length.
And I wanna know how to switch from sqlite to MySQL 
THANKS

**Comment by phpdave11** [comment]
I just pushed an update that allows you to use php-survey-builder with mysql.  Just modify config/Database.ini with the correct settings.

**Comment by phpdave11** [comment]
I also just pushed an update that adds support for PostgreSQL.

**Comment by smixy** [comment]
Thank you for your great work ! :)
