### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by macxi258** [phpdave11/php-survey-builder#7]
Hello Dave:
I hope you are fine. 
I am so interested to execute this project and already downloaded the app XAMPP. However, after I followed your instructions and run the server, I got a message: 
![imagen](https://user-images.githubusercontent.com/62798834/77823854-def8c380-70c3-11ea-8498-c091f3e5c2bd.png)

I modified the lines in the php.ini which appeared in the  Config menu 
![imagen](https://user-images.githubusercontent.com/62798834/77823874-fe8fec00-70c3-11ea-8cbe-c9a5bb679d94.png)
![imagen](https://user-images.githubusercontent.com/62798834/77823894-18313380-70c4-11ea-8029-f113fc675ac9.png)
However, its still not working. 

Could you help me with this issue. 
I will appreciate your help dave

**Comment by phpdave11** [comment]
Ensure that pdo_sqlite is enabled and shows up in `phpinfo();`
